import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'
import path from 'node:path'
import { createRequire } from 'node:module'

// The version shown on the Profile page, so a support email can say which build
// it came from. Read from package.json rather than duplicated, and inlined at
// build time — there is no package.json to read at runtime in a WebView.
const { version } = createRequire(import.meta.url)('./package.json')

// https://vitejs.dev/config/
//
// `--mode native` builds the bundle Capacitor wraps. The only difference is
// that the PWA plugin is skipped: a service worker never registers under the
// capacitor:// scheme, so registerSW.js would be dead weight that fails
// silently, and the native shell already serves the app locally.
export default defineConfig(({ mode }) => ({
  define: {
    __APP_VERSION__: JSON.stringify(version),
  },
  build: {
    // The only chunk above the default 500 KB is the RevenueCat Web Billing SDK
    // (~760 KB raw), and it is over by design: lazy behind the paywall, kept out
    // of the precached shell, and useless offline anyway. See globIgnores below.
    // Anything *else* crossing this line is a real regression worth the noise.
    chunkSizeWarningLimit: 800,
    rolldownOptions: {
      // @zxing/library's entry does `export * from './browser'`, dragging in its
      // legacy browser layer — BrowserPDF417Reader, BrowserAztecCodeReader and
      // friends — and every decoder behind them. The package ships no
      // `sideEffects: false`, so the bundler has to assume importing any of it
      // matters and keeps the lot: swapping the scanner to the one-dimensional
      // reader alone changed the chunk by nothing at all.
      //
      // Scoped to @zxing deliberately, rather than relaxing side effects
      // globally. It is a pure decoding library: nothing under it assigns to
      // `window`/`globalThis`, so there is no import whose only purpose is the
      // effect of running it.
      treeshake: {
        moduleSideEffects: [{ test: /node_modules[\\/]@zxing[\\/]/, sideEffects: false }],
      },
      output: {
        // Chunk names Rolldown derives from module ids are not ours to rely on:
        // the shared vendor chunk was landing as `Icon-*.js` while holding all
        // of supabase-js, and the RevenueCat chunk as `Purchases.es-*.js` — a
        // name owned by RevenueCat's build, which globIgnores below and
        // scripts/verify-precache.mjs both have to match. Naming the groups
        // here makes those two agreements about a string this repo controls.
        //
        // Deliberately no catch-all `vendor` group: one risks pulling a
        // lazily-reached dependency into the eagerly-loaded graph, which is the
        // opposite of what this is for. Everything unnamed keeps Rolldown's
        // automatic splitting.
        codeSplitting: {
          groups: [
            // Must stay its own lazy chunk — the service worker excludes it
            // from the shell by name.
            {
              name: 'purchases-web',
              test: /node_modules[\\/]@revenuecat[\\/]purchases-js/,
              priority: 30,
            },
            {
              name: 'supabase',
              test: /node_modules[\\/]@supabase[\\/]/,
              priority: 20,
            },
            // React and the router change far less often than app code, so a
            // chunk of their own survives an app deploy in the browser cache.
            {
              name: 'react-vendor',
              test: /node_modules[\\/](react|react-dom|scheduler|react-router)[\\/]/,
              priority: 10,
            },
          ],
        },
      },
    },
  },
  plugins: [
    react(),
    ...(mode === 'native' ? [] : [VitePWA({
      registerType: 'autoUpdate',
      // Icons generated by `pnpm exec pwa-assets-generator` from public/icon.svg.
      pwaAssets: {
        config: true,
      },
      manifest: {
        name: 'MacroTrack — Daily Macros Tracker',
        short_name: 'MacroTrack',
        description: 'Track your daily calories and macronutrients.',
        theme_color: '#6e56f8',
        background_color: '#f7f7fb',
        display: 'standalone',
        orientation: 'portrait',
        scope: '/',
        start_url: '/',
        categories: ['health', 'fitness', 'lifestyle'],
      },
      workbox: {
        // Precache the app shell so it launches offline.
        globPatterns: ['**/*.{js,css,html,svg,png,ico,woff2}'],
        // One chunk is deliberately *not* part of the shell: the RevenueCat Web
        // Billing SDK, ~200 KB gzipped behind a dynamic import that most sessions
        // never reach. Precaching it would make every first visit pay most of the
        // shell again for code that cannot work offline anyway — there is no
        // taking a payment without a network.
        //
        // The barcode scanner stays precached on purpose: scanning in a shop with
        // bad signal is a real thing this app is for. It is affordable now that it
        // only carries the one-dimensional readers — see BarcodeScanner.tsx.
        //
        // Named by the `purchases-web` code-splitting group above rather than by
        // whatever Rolldown would derive from the SDK's entry module.
        // `scripts/verify-precache.mjs` runs after the build and fails both if the
        // chunk lands in the manifest anyway and if the name matches nothing at
        // all, so a rename here is caught rather than silently regressing the shell.
        globIgnores: ['**/purchases-web-*.js'],
        navigateFallback: '/index.html',
        // Don't serve the SPA fallback for Supabase / API calls.
        navigateFallbackDenylist: [/^\/api/, /supabase\.co/],
        // No runtimeCaching for fonts any more: they are self-hosted under
        // /fonts and so are covered by the woff2 glob above, which precaches
        // them with the rest of the shell instead of fetching them once at
        // runtime and hoping the cache survives.
      },
      devOptions: {
        // Flip to true to exercise the service worker under `vite dev`.
        enabled: false,
      },
    })]),
  ],
  resolve: {
    alias: {
      // import.meta.dirname, not __dirname: Vite 8's native config loader has
      // no CommonJS wrapper to provide the latter, and warns that it is going
      // to become the default.
      '@': path.resolve(import.meta.dirname, './src'),
    },
  },
}))
