import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'
import path from 'node:path'

// https://vitejs.dev/config/
//
// `--mode native` builds the bundle Capacitor wraps. The only difference is
// that the PWA plugin is skipped: a service worker never registers under the
// capacitor:// scheme, so registerSW.js would be dead weight that fails
// silently, and the native shell already serves the app locally.
export default defineConfig(({ mode }) => ({
  plugins: [
    react(),
    ...(mode === 'native' ? [] : [VitePWA({
      registerType: 'autoUpdate',
      // Icons generated by `npx pwa-assets-generator` from public/icon.svg.
      pwaAssets: {
        config: true,
      },
      manifest: {
        name: 'MacroTrack — Daily Macros Tracker',
        short_name: 'MacroTrack',
        description: 'Track your daily calories and macronutrients.',
        theme_color: '#00685f',
        background_color: '#f8f9ff',
        display: 'standalone',
        orientation: 'portrait',
        scope: '/',
        start_url: '/',
        categories: ['health', 'fitness', 'lifestyle'],
      },
      workbox: {
        // Precache the app shell so it launches offline.
        globPatterns: ['**/*.{js,css,html,svg,png,ico,woff2}'],
        navigateFallback: '/index.html',
        // Don't serve the SPA fallback for Supabase / API calls.
        navigateFallbackDenylist: [/^\/api/, /supabase\.co/],
        // No runtimeCaching for fonts any more: they are self-hosted under
        // /fonts and so are covered by the woff2 glob above, which precaches
        // them with the rest of the shell instead of fetching them once at
        // runtime and hoping the cache survives.
      },
      devOptions: {
        // Flip to true to exercise the service worker under `vite dev`.
        enabled: false,
      },
    })]),
  ],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
}))
