#!/usr/bin/env node
/**
 * Assert that the generated iOS project is a real iPad app.
 *
 * Why this exists: `ios/` is gitignored and regenerated by `npx cap add ios` on
 * every build, so there is no checked-in project file to review. Capacitor's
 * template currently ships everything iPad needs — but a template change in a
 * future Capacitor release would silently turn MacroTrack back into an
 * iPhone-only app that runs letterboxed on an iPad, and nothing would fail.
 * This turns that into a build error.
 *
 * The three invariants, and why each matters:
 *
 *   1. TARGETED_DEVICE_FAMILY must include 2. Without it the app installs on
 *      iPad only in iPhone compatibility mode — scaled up, letterboxed.
 *   2. The ~ipad orientation list must include landscape. An iPad app that
 *      refuses to rotate reads as a blown-up phone app, and Apple expects iPad
 *      apps to work in both orientations.
 *   3. UIRequiresFullScreen must not be true. Setting it disables Split View
 *      and Slide Over, which is the main reason to have an iPad build at all.
 *
 * Run after `npx cap sync ios`; a no-op with a clear message when ios/ is absent
 * (a Linux CI runner, say), so it can sit unconditionally in the build script.
 */

import { readFileSync, existsSync } from 'node:fs'

const PBXPROJ = 'ios/App/App.xcodeproj/project.pbxproj'
const INFO_PLIST = 'ios/App/App/Info.plist'

/** Every TARGETED_DEVICE_FAMILY value in the project file. */
export function deviceFamilies(pbxproj) {
  return [...pbxproj.matchAll(/TARGETED_DEVICE_FAMILY = "?([\d,\s]+)"?;/g)].map((m) =>
    m[1]
      .split(',')
      .map((v) => v.trim())
      .filter(Boolean),
  )
}

/** True when every build configuration that declares a family includes iPad. */
export function targetsIpad(pbxproj) {
  const families = deviceFamilies(pbxproj)
  return families.length > 0 && families.every((f) => f.includes('2'))
}

/** The values of an <array> plist key, or null when the key is absent. */
export function plistArray(plist, key) {
  const escaped = key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const match = plist.match(new RegExp(`<key>${escaped}</key>\\s*<array>([\\s\\S]*?)</array>`))
  if (!match) return null
  return [...match[1].matchAll(/<string>([^<]+)<\/string>/g)].map((m) => m[1])
}

export function supportsIpadLandscape(plist) {
  const orientations = plistArray(plist, 'UISupportedInterfaceOrientations~ipad')
  if (!orientations) return false
  return (
    orientations.includes('UIInterfaceOrientationLandscapeLeft') &&
    orientations.includes('UIInterfaceOrientationLandscapeRight') &&
    orientations.includes('UIInterfaceOrientationPortrait')
  )
}

/** True when the plist forces full screen, which disables Split View. */
export function requiresFullScreen(plist) {
  return /<key>UIRequiresFullScreen<\/key>\s*<true\s*\/>/.test(plist)
}

export function checkAll(pbxproj, plist) {
  const failures = []
  if (!targetsIpad(pbxproj)) {
    failures.push(
      'TARGETED_DEVICE_FAMILY does not include iPad (2) in every build configuration — ' +
        'the app would install on iPad only in scaled iPhone compatibility mode.',
    )
  }
  if (!supportsIpadLandscape(plist)) {
    failures.push(
      'UISupportedInterfaceOrientations~ipad is missing portrait and both landscape ' +
        'orientations — an iPad app that cannot rotate reads as a blown-up phone app.',
    )
  }
  if (requiresFullScreen(plist)) {
    failures.push('UIRequiresFullScreen is true, which disables Split View and Slide Over.')
  }
  return failures
}

// Only run the checks when executed directly, so the predicates stay importable
// from the test.
if (process.argv[1] && import.meta.url.endsWith(process.argv[1].split('/').pop())) {
  if (!existsSync(PBXPROJ) || !existsSync(INFO_PLIST)) {
    console.log('verify-ipad: no ios/ project found, skipping (run `npx cap sync ios` first).')
    process.exit(0)
  }

  const failures = checkAll(readFileSync(PBXPROJ, 'utf8'), readFileSync(INFO_PLIST, 'utf8'))
  if (failures.length > 0) {
    console.error('verify-ipad: the generated iOS project is not a proper iPad app:\n')
    for (const f of failures) console.error(`  - ${f}`)
    console.error('\nCapacitor supplies all of this by default; a failure here usually means a')
    console.error('template change in a Capacitor upgrade. Fix it in the iOS project template')
    console.error('or add a post-sync patch step.')
    process.exit(1)
  }

  console.log('verify-ipad: iPad device family, orientations and Split View all OK.')
}
