#!/usr/bin/env node
/**
 * Assert that the generated Android project can actually open the camera.
 *
 * Why this exists: `android/` is gitignored and regenerated by `pnpm exec cap add
 * android` on every build, so there is no checked-in manifest to review — the
 * camera permission and the notification icon exist only because
 * scripts/patch-android-manifest.mjs and
 * scripts/patch-android-notification-icon.mjs ran. A workflow that forgets to
 * call them still produces a green build and a signed, uploadable AAB; the
 * breakage only surfaces on a user's device, as a barcode scanner that reports a
 * denial the user was never asked to make. That is precisely what happened: the
 * release workflow shipped without either patch step. This turns the next
 * omission into a build error.
 *
 * The invariants, and why each matters:
 *
 *   1. `android.permission.CAMERA` must be declared. Android denies an
 *      undeclared permission immediately and silently, so the WebView's
 *      getUserMedia request rejects with NotAllowedError and the scanner renders
 *      "you denied camera access" with no prompt and nothing in logcat. See the
 *      header of scripts/patch-android-manifest.mjs for the full trace.
 *   2. `android.hardware.camera` and `android.hardware.camera.autofocus` must
 *      both be declared with `required="false"`. Declaring the CAMERA permission
 *      makes Google Play *imply* both as required, which delists the app on every
 *      device without an autofocus rear camera — for a feature that is one of
 *      several ways to add a food.
 *   3. An `ic_stat_water_drop` resource must exist under some `res/drawable`
 *      qualifier directory. capacitor.config.ts names it as the hydration
 *      reminder's small icon; without the resource Android falls back to the
 *      full-colour launcher icon, which the status bar draws as a solid grey
 *      blob.
 *
 * Deliberately asserts the *result* rather than which script produced it. A
 * future ML-Kit barcode plugin would contribute the CAMERA permission through
 * its own merged manifest, at which point patch-android-manifest.mjs no-ops by
 * design — and this must keep passing, because the shipped app is still correct.
 *
 * Run after the patch scripts; a no-op with a clear message when android/ is
 * absent (a macOS iOS-only run, say), so it can sit unconditionally in a build
 * script and never fail a build.
 */

import { readFileSync, existsSync, readdirSync } from 'node:fs'
import { join } from 'node:path'

const MANIFEST = 'android/app/src/main/AndroidManifest.xml'
const RES_DIR = 'android/app/src/main/res'

/** The notification small icon named by capacitor.config.ts. */
export const NOTIFICATION_ICON = 'ic_stat_water_drop'

/** The two features Play would otherwise imply as required. */
export const OPTIONAL_FEATURES = ['android.hardware.camera', 'android.hardware.camera.autofocus']

/**
 * The attributes of every tag of type `tag` in `xml`.
 *
 * Attribute order inside an XML tag carries no meaning, and the manifest merger
 * is free to rewrite it — so parse the attributes rather than matching a literal
 * line. Each entry is a plain object of attribute name to value.
 */
export function tagAttributes(xml, tag) {
  const tags = [...xml.matchAll(new RegExp(`<${tag}\\s([^>]*?)/?>`, 'g'))]
  return tags.map((m) =>
    Object.fromEntries(
      [...m[1].matchAll(/([\w:.-]+)\s*=\s*"([^"]*)"/g)].map((a) => [a[1], a[2]]),
    ),
  )
}

/**
 * True when `manifest` declares the CAMERA permission.
 *
 * Asserts presence only, not provenance: the permission is equally correct
 * whether patch-android-manifest.mjs inserted it or a plugin's manifest merged
 * it in.
 */
export function hasCameraPermission(manifest) {
  return tagAttributes(manifest, 'uses-permission').some(
    (a) => a['android:name'] === 'android.permission.CAMERA',
  )
}

/**
 * The `android:required` value declared for `feature`, or null when the
 * `uses-feature` element is absent entirely.
 *
 * Absent and `required="true"` are different failures with the same
 * consequence, and saying which one it is makes the error actionable.
 */
export function featureRequirement(manifest, feature) {
  const tag = tagAttributes(manifest, 'uses-feature').find((a) => a['android:name'] === feature)
  if (!tag) return null
  // Android's default when the attribute is omitted is `true` — which is the
  // delisting case, so it must not read as optional.
  return tag['android:required'] ?? 'true'
}

/** True when `feature` is declared and explicitly optional. */
export function hasOptionalFeature(manifest, feature) {
  return featureRequirement(manifest, feature) === 'false'
}

/**
 * The entries of `files` that are a notification icon resource.
 *
 * `files` is a list of paths relative to res/. Matched loosely — any `drawable`
 * qualifier directory (`drawable`, `drawable-night`, `drawable-hdpi`…) and any
 * extension, so this holds whether the icon stays a single vector drawable or
 * becomes five PNG densities.
 */
export function notificationIcons(files) {
  return files.filter((f) => /(^|\/)drawable[^/]*\/ic_stat_water_drop[^/]*$/.test(f))
}

/** Every file under `dir`, as paths relative to `dir`. */
export function listFiles(dir, prefix = '') {
  if (!existsSync(dir)) return []
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const rel = prefix ? `${prefix}/${entry.name}` : entry.name
    return entry.isDirectory() ? listFiles(join(dir, entry.name), rel) : [rel]
  })
}

export function checkAll(manifest, resFiles) {
  const failures = []

  if (!hasCameraPermission(manifest)) {
    failures.push(
      'android.permission.CAMERA is not declared — Android denies the WebView\'s camera ' +
        'request without ever prompting, and the barcode scanner reports a denial the user ' +
        'never made. Did scripts/patch-android-manifest.mjs run after `cap sync android`?',
    )
  }

  for (const feature of OPTIONAL_FEATURES) {
    const required = featureRequirement(manifest, feature)
    if (required === null) {
      failures.push(
        `<uses-feature android:name="${feature}" android:required="false" /> is missing — ` +
          'declaring the CAMERA permission makes Google Play imply this feature as required ' +
          'and delist the app on devices without an autofocus rear camera.',
      )
    } else if (required !== 'false') {
      failures.push(
        `${feature} is declared with android:required="${required}", not "false" — Play would ` +
          'delist the app on devices without an autofocus rear camera. Scanning is optional ' +
          'here; search and manual entry need no camera.',
      )
    }
  }

  if (notificationIcons(resFiles).length === 0) {
    failures.push(
      `No res/drawable*/${NOTIFICATION_ICON}* resource — capacitor.config.ts names it as the ` +
        'hydration reminder\'s small icon, and without it Android falls back to the ' +
        'full-colour launcher icon, which the status bar draws as a grey blob. Did ' +
        'scripts/patch-android-notification-icon.mjs run after `cap sync android`?',
    )
  }

  return failures
}

// Only run the checks when executed directly, so the predicates stay importable
// from the test.
if (process.argv[1] && import.meta.url.endsWith(process.argv[1].split('/').pop())) {
  if (!existsSync(MANIFEST)) {
    console.log(
      'verify-android: no android/ project found, skipping (run `pnpm exec cap sync android` first).',
    )
    process.exit(0)
  }

  const failures = checkAll(readFileSync(MANIFEST, 'utf8'), listFiles(RES_DIR))
  if (failures.length > 0) {
    console.error('verify-android: the generated Android project would ship broken:\n')
    for (const f of failures) console.error(`  - ${f}`)
    console.error('\nNone of this is contributed by Capacitor\'s template or by a plugin: it comes')
    console.error('from scripts/patch-android-manifest.mjs and')
    console.error('scripts/patch-android-notification-icon.mjs, which must run after')
    console.error('`cap sync android` in every workflow that produces an APK or AAB.')
    process.exit(1)
  }

  console.log(
    'verify-android: CAMERA permission, optional camera features and the notification icon all OK.',
  )
}
